declare const __brand: unique symbol;
type Brand<T, B extends string> = T & {
    readonly [__brand]: B;
};
export type TenantId = Brand<string, 'TenantId'>;
export type IncidentId = Brand<string, 'IncidentId'>;
export type IntegrationId = Brand<string, 'IntegrationId'>;
export type EvidenceId = Brand<string, 'EvidenceId'>;
export type AuditEntryId = Brand<string, 'AuditEntryId'>;
export type RemediationId = Brand<string, 'RemediationId'>;
export type PatternId = Brand<string, 'PatternId'>;
export type FeedbackId = Brand<string, 'FeedbackId'>;
export type ServiceNodeId = Brand<string, 'ServiceNodeId'>;
export type EdgeId = Brand<string, 'EdgeId'>;
export type ChangeEventId = Brand<string, 'ChangeEventId'>;
export declare function tenantId(id: string): TenantId;
export declare function incidentId(id: string): IncidentId;
export declare function integrationId(id: string): IntegrationId;
export declare function evidenceId(id: string): EvidenceId;
export declare function auditEntryId(id: string): AuditEntryId;
export declare function remediationId(id: string): RemediationId;
export declare function patternId(id: string): PatternId;
export declare function feedbackId(id: string): FeedbackId;
export declare function serviceNodeId(id: string): ServiceNodeId;
export declare function edgeId(id: string): EdgeId;
export declare function changeEventId(id: string): ChangeEventId;
export type NotificationId = Brand<string, 'NotificationId'>;
export type ApprovalId = Brand<string, 'ApprovalId'>;
export type ApiKeyId = Brand<string, 'ApiKeyId'>;
export declare function notificationId(id: string): NotificationId;
export declare function approvalId(id: string): ApprovalId;
export declare function apiKeyId(id: string): ApiKeyId;
export type TriggerId = Brand<string, 'TriggerId'>;
export declare function triggerId(id: string): TriggerId;
export type BillingAccountId = Brand<string, 'BillingAccountId'>;
export type UsageRecordId = Brand<string, 'UsageRecordId'>;
export declare function billingAccountId(id: string): BillingAccountId;
export declare function usageRecordId(id: string): UsageRecordId;
export {};
