import type { PricingPlan } from '../types';

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: 99,
    annualPrice: 84,
    investigations: '15/month',
    events: '500/month',
    rateLimit: '100 req/min',
    overage: '$8.99/each',
    eventOverage: '$0.20/each',
    target: 'Small teams',
    features: [
      'All integrations',
      'Audit trail',
      'Knowledge Base',
      'Remediation (PRs)',
      'RBAC',
      'Email support',
    ],
    cta: 'Self-host',
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 349,
    annualPrice: 297,
    investigations: '60/month',
    events: '3,000/month',
    rateLimit: '500 req/min',
    overage: '$8.99/each',
    eventOverage: '$0.20/each',
    target: 'Growing teams',
    features: [
      'All integrations',
      'Audit trail',
      'Knowledge Base',
      'Remediation (PRs)',
      'RBAC',
      'Email + WhatsApp support',
    ],
    cta: 'Self-host',
    highlighted: true,
  },
  {
    id: 'business',
    name: 'Business',
    price: 899,
    annualPrice: 719,
    investigations: '200/month',
    events: '10,000/month',
    rateLimit: '2,000 req/min',
    overage: '$8.99/each',
    eventOverage: '$0.20/each',
    target: 'Organizations',
    features: [
      'All integrations',
      'Audit trail',
      'Knowledge Base',
      'Remediation (PRs)',
      'RBAC',
      'Email + WhatsApp support',
    ],
    cta: 'Self-host',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 'Custom',
    annualPrice: 'Negotiated',
    investigations: 'Custom',
    events: 'Custom',
    rateLimit: 'Custom',
    overage: 'Negotiated',
    eventOverage: 'Negotiated',
    target: '50+ devs',
    features: [
      'All + custom integrations',
      'Audit trail',
      'Knowledge Base',
      'Remediation (PRs)',
      'RBAC + SSO/SAML',
      'Email + WhatsApp + Dedicated support + SLA',
    ],
    cta: 'View on GitHub',
  },
];

export const QUOTA_PACKS = [
  {
    id: 'investigations-10',
    name: '10 investigations',
    price: 79,
    perUnit: '$7.90/each',
  },
  {
    id: 'events-1000',
    name: '1,000 events',
    price: 99,
    perUnit: '$0.099/each',
  },
];
