import type { IIncidentRepository } from '../../ingestion/domain/incident.repository.js';
import type { IEvidenceRepository } from '../../triage/domain/evidence.repository.js';
import type { IEventBus } from '../../../shared/domain/events.js';
import type { AgentRunner } from '../../../shared/application/ports/agent-runner.port.js';
import type { LLMClient } from '../../../shared/application/ports/llm-client.port.js';
import type { CloudProvider, CloudCredentials } from '../../../shared/application/ports/cloud-provider.port.js';
import type { CredentialVendor } from '../../../shared/application/ports/credential-vendor.port.js';
import type { MessageQueue } from '../../../shared/application/ports/message-queue.port.js';
import type { InvestigationResult, InvestigationInput } from '../domain/investigation.types.js';
import type { ICodeRepository } from '../../../shared/application/ports/code-repository.port.js';
import type { ICodeKnowledgeRepository } from '../../code-intelligence/domain/code-knowledge.repository.js';
import type { IRelayGateway } from '../../../shared/application/ports/relay-gateway.port.js';
import type { OAuthTokenStore } from '../../../shared/application/ports/oauth-token-store.port.js';
import type { IntegrationToolProvider } from '../../../shared/application/ports/integration-tool-provider.port.js';
import type { AgentMemory } from '../../../shared/application/ports/agent-memory.port.js';
import type { TenantId, IncidentId } from '../../../shared/domain/value-objects.js';
export type ToolHandlerFactory = (deps: {
    cloudProvider: CloudProvider;
    cloudCredentials: CloudCredentials;
    incidentRepo: IIncidentRepository;
    tenantId: TenantId;
    incidentId: IncidentId;
    agentMemory?: AgentMemory;
    codeRepo?: ICodeRepository;
    codeKnowledgeRepo?: ICodeKnowledgeRepository;
    knownRepos?: string[];
    relayGateway?: IRelayGateway;
    oauthTokenStore?: OAuthTokenStore;
    integrationToolProvider?: IntegrationToolProvider;
}) => (name: string, input: Record<string, unknown>) => Promise<string>;
export interface InvestigateIncidentDeps {
    incidentRepo: IIncidentRepository;
    evidenceRepo: IEvidenceRepository;
    eventBus: IEventBus;
    agentRunner: AgentRunner;
    llmClient: LLMClient;
    cloudProvider: CloudProvider;
    credentialVendor?: CredentialVendor;
    toolHandlerFactory: ToolHandlerFactory;
    messageQueue?: MessageQueue;
    remediationQueueUrl?: string;
    defaultRegion?: string;
    codeRepoFactory?: (tenantId: TenantId) => ICodeRepository | undefined;
    codeKnowledgeRepo?: ICodeKnowledgeRepository;
    synthesisModel?: string;
    relayGateway?: IRelayGateway;
    oauthTokenStore?: OAuthTokenStore;
    integrationToolProvider?: IntegrationToolProvider;
    agentMemory?: AgentMemory;
}
export declare class InvestigateIncidentUseCase {
    private readonly incidentRepo;
    private readonly evidenceRepo;
    private readonly eventBus;
    private readonly agentRunner;
    private readonly llmClient;
    private readonly cloudProvider;
    private readonly credentialVendor?;
    private readonly toolHandlerFactory;
    private readonly messageQueue?;
    private readonly remediationQueueUrl?;
    private readonly defaultRegion;
    private readonly codeRepoFactory?;
    private readonly codeKnowledgeRepo?;
    private readonly synthesisModel?;
    private readonly relayGateway?;
    private readonly oauthTokenStore?;
    private readonly integrationToolProvider?;
    private readonly agentMemory?;
    constructor(deps: InvestigateIncidentDeps);
    execute(input: InvestigationInput): Promise<InvestigationResult>;
    private runAgentWave;
    private runCodeFixer;
    private parseProposedFix;
}
